#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import re
import sys
from difflib import SequenceMatcher

songs = {
"baroriginal": {"album": "Anthology 2", "name": "12-Bar Original", "songwriter": "John Lennon\nPaul McCartney\nGeorge Harrison\nRingo Starr", "notes": "", "vocal": "Instrumental", "year": "1965"},
"acrosstheuniverse": {"album": "Let It Be", "name": "Across the Universe", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"actnaturally": {"album": "UK: Help! US: Yesterday and Today", "name": "Act Naturally", "songwriter": "Johnny Russell\nVoni Morrison", "notes": "Cover", "vocal": "Starr", "year": "1965"},
"aintshesweet": {"album": "Anthology 1", "name": "Ain't She Sweet", "songwriter": "Jack Yellen\nMilton Ager", "notes": "Cover", "vocal": "Lennon", "year": "1961"},
"allivegottodo": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "All I've Got to Do", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1963"},
"allmyloving": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "All My Loving", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1963"},
"allthingsmustpass": {"album": "Anthology 3", "name": "All Things Must Pass", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1969"},
"alltogethernow": {"album": "Yellow Submarine", "name": "All Together Now", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1967"},
"allyouneedislove": {"album": "Magical Mystery Tour", "name": "All You Need Is Love", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1967"},
"andiloveher": {"album": "UK: A Hard Day's Night US: Something New", "name": "And I Love Her", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1964"},
"andyourbirdcansing": {"album": "UK: Revolver US: Yesterday and Today", "name": "And Your Bird Can Sing", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1966"},
"annagotohim": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Anna (Go to Him)", "songwriter": "Arthur Alexander", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"anothergirl": {"album": "Help!", "name": "Another Girl", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1965"},
"anytimeatall": {"album": "UK: A Hard Day's Night US: Something New", "name": "Any Time at All", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1964"},
"askmewhy": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Ask Me Why", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1962"},
"babyitsyou": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Baby It's You", "songwriter": "Burt Bacharach\nHal David\nLuther Dixon", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"babyyourearichman": {"album": "Magical Mystery Tour", "name": "Baby, You're a Rich Man", "songwriter": "Lennon\nMcCartney", "notes": "Non-album single\nB-side of \"All You Need is Love\"", "vocal": "Lennon", "year": "1967"},
"babysinblack": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "Baby's in Black", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1964"},
"backintheussr": {"album": "The Beatles", "name": "Back in the U.S.S.R.", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"badboy": {"album": "UK: A Collection of Beatles Oldies US: Beatles VI", "name": "Bad Boy", "songwriter": "Larry Williams", "notes": "Cover", "vocal": "Lennon", "year": "1965"},
"badtome": {"album": "The Beatles Bootleg Recordings 1963", "name": "Bad to Me", "songwriter": "Lennon", "notes": "Written for Billy J. Kramer", "vocal": "Lennon", "year": "1963"},
"theballadofjohnandyoko": {"album": "UK: 1967–1970 US: Hey Jude", "name": "The Ballad of John and Yoko", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1969"},
"beautifuldreamer": {"album": "On Air – Live at the BBC Volume 2", "name": "Beautiful Dreamer", "songwriter": "Stephen Foster", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"because": {"album": "Abbey Road", "name": "Because", "songwriter": "Lennon[25]", "notes": "", "vocal": "Lennon, McCartney, Harrison", "year": "1969"},
"becauseiknowyoulovemeso": {"album": "Let It Be... Naked - Fly on the Wall bonus disc", "name": "Because I Know You Love Me So", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1969"},
"beingforthebenefitofmrkite": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Being for the Benefit of Mr. Kite!", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1967"},
"bsamemucho": {"album": "Anthology 1", "name": "Bésame Mucho", "songwriter": "Consuelo Velázquez\nSunny Skylar", "notes": "Cover", "vocal": "McCartney", "year": "1962"},
"birthday": {"album": "The Beatles", "name": "Birthday", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "McCartney, with Lennon", "year": "1968"},
"blackbird": {"album": "The Beatles", "name": "Blackbird", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"bluejayway": {"album": "Magical Mystery Tour", "name": "Blue Jay Way", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1967"},
"boys": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Boys", "songwriter": "Luther Dixon\nWes Farrell", "notes": "Cover", "vocal": "Starr", "year": "1963"},
"cantbuymelove": {"album": "UK: A Hard Day's Night US: Hey Jude", "name": "Can't Buy Me Love", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, with Lennon", "year": "1964"},
"carol": {"album": "Live at the BBC", "name": "Carol", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"carrythatweight": {"album": "Abbey Road", "name": "Carry That Weight", "songwriter": "McCartney[32]", "notes": "", "vocal": "McCartney, with Lennon, Harrison, and Starr", "year": "1969"},
"catswalk": {"album": "N/A", "name": "Catswalk", "songwriter": "McCartney", "notes": "", "vocal": "N/A", "year": "1962"},
"cayenne": {"album": "Anthology 1", "name": "Cayenne", "songwriter": "McCartney", "notes": "", "vocal": "Instrumental", "year": "1960"},
"chains": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Chains", "songwriter": "Gerry Goffin\nCarole King", "notes": "Cover", "vocal": "Harrison, (with Lennon, McCartney)", "year": "1963"},
"childofnature": {"album": "Let It Be... Naked - Fly on the Wall bonus disc", "name": "Child of Nature", "songwriter": "Lennon", "notes": "Turned into Lennon's \"Jealous Guy\"", "vocal": "Lennon", "year": "1968"},
"christmastimeishereagain": {"album": "The Beatles' Christmas Album", "name": "Christmas Time (Is Here Again)", "songwriter": "Lennon\nMcCartney\nHarrison\nStarr", "notes": "Non-album single\nB-side of \"Free As A Bird\"", "vocal": "Lennon, McCartney, Harrison, Starr", "year": "1967"},
"circles": {"album": "", "name": "Circles", "songwriter": "Harrison", "notes": "On Harrison's Gone Troppo", "vocal": "Harrison", "year": "1968"},
"clarabella": {"album": "Live at the BBC", "name": "Clarabella", "songwriter": "Mike Pingitore", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"comeandgetit": {"album": "Anthology 3", "name": "Come and Get It", "songwriter": "McCartney", "notes": "Recorded by Badfinger", "vocal": "McCartney", "year": "1969"},
"cometogether": {"album": "Abbey Road", "name": "Come Together", "songwriter": "Lennon[33]", "notes": "Double A-side single with \"Something\"", "vocal": "Lennon", "year": "1969"},
"thecontinuingstoryofbungalowbill": {"album": "The Beatles", "name": "The Continuing Story of Bungalow Bill", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"crybabycry": {"album": "The Beatles", "name": "Cry Baby Cry", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1968"},
"cryforashadow": {"album": "Anthology 1", "name": "Cry for a Shadow", "songwriter": "Lennon and Harrison", "notes": "", "vocal": "Instrumental", "year": "1961"},
"cryingwaitinghoping": {"album": "Live at the BBC", "name": "Crying, Waiting, Hoping", "songwriter": "Buddy Holly", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"adayinthelife": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "A Day in the Life", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1967"},
"daytripper": {"album": "UK: A Collection of Beatles Oldies US: Yesterday and Today", "name": "Day Tripper", "songwriter": "Lennon\n(with McCartney)", "notes": "Double A-side with \"We Can Work It Out\",[23][14]\n\"Dear Prudence\"\"\"", "vocal": "Lennon, McCartney", "year": "1965"},
"devilinherheart": {"album": "UK: With the Beatles US: The Beatles' Second Album", "name": "Devil in Her Heart", "songwriter": "Drapkin (a.k.a. Ricky Dee)", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"digapony": {"album": "Let It Be", "name": "Dig a Pony", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1969"},
"digit": {"album": "Let It Be", "name": "Dig It", "songwriter": "Lennon\nMcCartney\nHarrison\nStarr", "notes": "", "vocal": "Lennon", "year": "1969"},
"dizzymisslizzy": {"album": "UK: Help! US: Beatles VI", "name": "Dizzy, Miss Lizzy", "songwriter": "Larry Williams", "notes": "Cover", "vocal": "Lennon", "year": "1965"},
"doyouwanttoknowasecret": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Do You Want to Know a Secret?", "songwriter": "Lennon", "notes": "", "vocal": "Harrison", "year": "1963"},
"doctorrobert": {"album": "UK: Revolver US: Yesterday and Today", "name": "Doctor Robert", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1966"},
"dontbotherme": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "Don't Bother Me", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1963"},
"donteverchange": {"album": "Live at the BBC", "name": "Don't Ever Change", "songwriter": "Gerry Goffin\nCarole King", "notes": "Cover", "vocal": "Harrison and McCartney", "year": "1963"},
"dontletmedown": {"album": "UK: 1967–1970 US: Hey Jude", "name": "Don't Let Me Down", "songwriter": "Lennon", "notes": "Non-album single\nB-side of \"Get Back\"", "vocal": "Lennon (with McCartney)", "year": "1969"},
"dontpassmeby": {"album": "The Beatles", "name": "Don't Pass Me By", "songwriter": "Starkey[b]", "notes": "", "vocal": "Starr", "year": "1968"},
"drivemycar": {"album": "UK: Rubber Soul US: Yesterday and Today", "name": "Drive My Car", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1965"},
"eightdaysaweek": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "Eight Days a Week", "songwriter": "McCartney\n(with Lennon)", "notes": "US single only", "vocal": "Lennon, with McCartney", "year": "1964"},
"eleanorrigby": {"album": "Revolver", "name": "Eleanor Rigby", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1966"},
"theend": {"album": "Abbey Road", "name": "The End", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"etcetera": {"album": "Unreleased", "name": "Etcetera", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"everylittlething": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "Every Little Thing", "songwriter": "McCartney", "notes": "", "vocal": "Lennon, with McCartney", "year": "1964"},
"everybodysgotsomethingtohideexceptmeandmymonkey": {"album": "The Beatles", "name": "Everybody's Got Something to Hide Except Me and My Monkey", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"everybodystryingtobemybaby": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "Everybody's Trying to Be My Baby", "songwriter": "Carl Perkins", "notes": "Cover", "vocal": "Harrison", "year": "1964"},
"fixingahole": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Fixing a Hole", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1967"},
"fancymychanceswithyou": {"album": "Let It Be... Naked - Fly on the Wall bonus disc", "name": "Fancy My Chances with You", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1969"},
"flying": {"album": "Magical Mystery Tour", "name": "Flying", "songwriter": "Lennon\nMcCartney\nHarrison\nStarr", "notes": "", "vocal": "Instrumental", "year": "1967"},
"thefoolonthehill": {"album": "Magical Mystery Tour", "name": "The Fool on the Hill", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1967"},
"fornoone": {"album": "Revolver", "name": "For No One", "songwriter": "McCartney", "notes": "Featuring Alan Civil on French horn", "vocal": "McCartney", "year": "1966"},
"foryoublue": {"album": "Let It Be", "name": "For You Blue", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1969"},
"freeasabird": {"album": "Anthology 1", "name": "Free as a Bird", "songwriter": "Lennon\nMcCartney\nHarrison\nStarr", "notes": "", "vocal": "Lennon, McCartney and Harrison", "year": "1977"},
"frommetoyou": {"album": "UK: A Collection of Beatles Oldies US: 1962–1966", "name": "From Me to You", "songwriter": "Lennon\nMcCartney", "notes": "Non-album single", "vocal": "Lennon, McCartney", "year": "1963"},
"fromustoyou": {"album": "Live at the BBC", "name": "From Us to You", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1963"},
"getback": {"album": "Let It Be", "name": "Get Back", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"gettingbetter": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Getting Better", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1967"},
"girl": {"album": "Rubber Soul", "name": "Girl", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1965"},
"gladallover": {"album": "Live at the BBC", "name": "Glad All Over", "songwriter": "Roy C. Bennett\nSid Tepper\nAaron Schroeder", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"glassonion": {"album": "The Beatles", "name": "Glass Onion", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"goldenslumbers": {"album": "Abbey Road", "name": "Golden Slumbers", "songwriter": "McCartney[32]", "notes": "", "vocal": "McCartney", "year": "1969"},
"gooddaysunshine": {"album": "Revolver", "name": "Good Day Sunshine", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1966"},
"goodmorninggoodmorning": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Good Morning Good Morning", "songwriter": "Lennon", "notes": "McCartney plays guitar solo", "vocal": "Lennon", "year": "1967"},
"goodnight": {"album": "The Beatles", "name": "Good Night", "songwriter": "Lennon", "notes": "", "vocal": "Starr", "year": "1968"},
"goodbye": {"album": "", "name": "Goodbye", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"gottogetyouintomylife": {"album": "Revolver", "name": "Got to Get You into My Life", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1966"},
"hallelujahiloveherso": {"album": "Anthology 1", "name": "Hallelujah, I Love Her So", "songwriter": "Ray Charles", "notes": "Cover", "vocal": "McCartney", "year": "1960"},
"happinessisawarmgun": {"album": "The Beatles", "name": "Happiness Is a Warm Gun", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"aharddaysnight": {"album": "UK: A Hard Day's Night US: 1962–1966", "name": "A Hard Day's Night", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon, with McCartney", "year": "1964"},
"heather": {"album": "", "name": "Heather", "songwriter": "McCartney", "notes": "Donovan plays on the demo", "vocal": "McCartney", "year": "1968"},
"hellogoodbye": {"album": "Magical Mystery Tour", "name": "Hello, Goodbye", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1967"},
"hellolittlegirl": {"album": "Anthology 1", "name": "Hello Little Girl", "songwriter": "Lennon", "notes": "Recorded by The Fourmost\nreleased August 1963", "vocal": "Lennon", "year": "1962"},
"help": {"album": "Help!", "name": "Help!", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1965"},
"helterskelter": {"album": "The Beatles", "name": "Helter Skelter", "songwriter": "McCartney", "notes": "Featuring Starr with shouted words in stereo version", "vocal": "McCartney", "year": "1968"},
"hermajesty": {"album": "Abbey Road", "name": "Her Majesty", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"herecomesthesun": {"album": "Abbey Road", "name": "Here Comes the Sun", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1969"},
"herethereandeverywhere": {"album": "Revolver", "name": "Here, There and Everywhere", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1966"},
"heybulldog": {"album": "Yellow Submarine", "name": "Hey Bulldog", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1968"},
"heyjude": {"album": "UK: 1967–1970 US: Hey Jude", "name": "Hey Jude", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"hippyhippyshake": {"album": "Live at the BBC", "name": "Hippy Hippy Shake", "songwriter": "Chan Romero", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"holdmetight": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "Hold Me Tight", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1963"},
"honeydont": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "Honey Don't", "songwriter": "Carl Perkins", "notes": "Cover", "vocal": "Starr", "year": "1964"},
"honeypie": {"album": "The Beatles", "name": "Honey Pie", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"thehoneymoonsong": {"album": "Live at the BBC", "name": "The Honeymoon Song", "songwriter": "Mikis Theodorakis\nSansom", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"howdoyoudoit": {"album": "Anthology 1", "name": "How Do You Do It?", "songwriter": "Mitch Murray", "notes": "Cover", "vocal": "Lennon", "year": "1962"},
"iamthewalrus": {"album": "Magical Mystery Tour", "name": "I Am the Walrus", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1967"},
"icallyourname": {"album": "UK: \"Long Tall Sally\" EP US: The Beatles' Second Album", "name": "I Call Your Name", "songwriter": "Lennon", "notes": "First release by Billy J Kramer with the Dakotas\n(July 1963)", "vocal": "Lennon", "year": "1964"},
"idontwanttospoiltheparty": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "I Don't Want to Spoil the Party", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1964"},
"ifeelfine": {"album": "UK: A Collection of Beatles Oldies US: Beatles '65", "name": "I Feel Fine", "songwriter": "Lennon", "notes": "Non-album single", "vocal": "Lennon", "year": "1964"},
"iforgottoremembertoforget": {"album": "Live at the BBC", "name": "I Forgot to Remember to Forget", "songwriter": "Stan Kesler and Charlie Feathers", "notes": "Cover", "vocal": "Harrison", "year": "1964"},
"igotawoman": {"album": "Live at the BBC", "name": "I Got a Woman", "songwriter": "Ray Charles", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"igottofindmybaby": {"album": "Live at the BBC", "name": "I Got to Find My Baby", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"ijustdontunderstand": {"album": "Live at the BBC", "name": "I Just Don't Understand", "songwriter": "Marijohn Wilkin\nKent Westberry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"ilostmylittlegirl": {"album": "", "name": "I Lost My Little Girl", "songwriter": "McCartney", "notes": "", "vocal": "Lennon", "year": "1962"},
"imemine": {"album": "Let It Be", "name": "I Me Mine", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1970"},
"ineedyou": {"album": "Help!", "name": "I Need You", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1965"},
"isawherstandingthere": {"album": "UK: Please Please Me US: Meet the Beatles!", "name": "I Saw Her Standing There", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1963"},
"ishouldhaveknownbetter": {"album": "UK: A Hard Day's Night US: Hey Jude", "name": "I Should Have Known Better", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1964"},
"iwannabeyourman": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "I Wanna Be Your Man", "songwriter": "McCartney\n(with Lennon)", "notes": "Written for the Rolling Stones", "vocal": "Starr", "year": "1963"},
"iwanttoholdyourhand": {"album": "UK: A Collection of Beatles Oldies US: Meet the Beatles!", "name": "I Want to Hold Your Hand", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1963"},
"iwanttotellyou": {"album": "Revolver", "name": "I Want to Tell You", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1966"},
"iwantyoushessoheavy": {"album": "Abbey Road", "name": "I Want You (She's So Heavy)", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1969"},
"iwill": {"album": "The Beatles", "name": "I Will", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"ififell": {"album": "UK: A Hard Day's Night US: Something New", "name": "If I Fell", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1964"},
"ifineededsomeone": {"album": "UK: Rubber Soul US: Yesterday and Today", "name": "If I Needed Someone", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1965"},
"ifyouvegottrouble": {"album": "Anthology 2", "name": "If You've Got Trouble", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Starr", "year": "1965"},
"illbeback": {"album": "UK: A Hard Day's Night US: Beatles '65", "name": "I'll Be Back", "songwriter": "Lennon", "notes": "", "vocal": "Lennon and McCartney)", "year": "1964"},
"illbeonmyway": {"album": "Live at the BBC", "name": "I'll Be on My Way", "songwriter": "McCartney", "notes": "Single by Billy J Kramer with the Dakotas\n(April 1963)", "vocal": "Lennon", "year": "1963"},
"illcryinstead": {"album": "UK: A Hard Day's Night US: Something New", "name": "I'll Cry Instead", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1964"},
"illfollowthesun": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "I'll Follow the Sun", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, with Lennon", "year": "1964"},
"illgetyou": {"album": "UK: Past Masters Volume 1 US: The Beatles' Second Album", "name": "I'll Get You", "songwriter": "Lennon\nMcCartney", "notes": "Non-album single\nB-side of \"She Loves You\",[51]\n\"I'm a Loser\"\"\"", "vocal": "Lennon, with McCartney", "year": "1963"},
"imdown": {"album": "Rock 'n' Roll Music", "name": "I'm Down", "songwriter": "McCartney", "notes": "Non-album single\nB-side of \"Help!\",\n\"I'm Gonna Sit Right Down and Cry (Over You)\"\"\"", "vocal": "McCartney", "year": "1965"},
"imhappyjusttodancewithyou": {"album": "UK: A Hard Day's Night US: Something New", "name": "I'm Happy Just to Dance with You", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Harrison", "year": "1964"},
"iminlove": {"album": "The Beatles Bootleg Recordings 1963", "name": "I'm In Love", "songwriter": "Lennon", "notes": "Written for The Fourmost\n(single released November 1963)", "vocal": "Lennon", "year": "1963"},
"imlookingthroughyou": {"album": "Rubber Soul", "name": "I'm Looking Through You", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, with Lennon", "year": "1965"},
"imonlysleeping": {"album": "UK: Revolver US: Yesterday and Today", "name": "I'm Only Sleeping", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1966"},
"imsotired": {"album": "The Beatles", "name": "I'm So Tired", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"imtalkingaboutyou": {"album": "Live! at the Star-Club in Hamburg, Germany; 1962", "name": "I'm Talking About You", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1962"},
"inmylife": {"album": "Rubber Soul", "name": "In My Life", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon", "year": "1965"},
"inspiteofallthedanger": {"album": "Anthology 1", "name": "In Spite of All the Danger", "songwriter": "McCartney and Harrison", "notes": "", "vocal": "Lennon", "year": "1958"},
"theinnerlight": {"album": "UK: Rarities US: Rarities", "name": "The Inner Light", "songwriter": "Harrison", "notes": "Non-album single\nB-side of \"Lady Madonna\",\n\"It Won't Be Long\"\"\"", "vocal": "Harrison", "year": "1968"},
"itsalltoomuch": {"album": "Yellow Submarine", "name": "It's All Too Much", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1967"},
"itsonlylove": {"album": "UK: Help! US: Rubber Soul", "name": "It's Only Love", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1965"},
"ivegotafeeling": {"album": "Let It Be", "name": "I've Got a Feeling", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1969"},
"ivejustseenaface": {"album": "UK: Help! US: Rubber Soul", "name": "I've Just Seen a Face", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1965"},
"jazzpianosong": {"album": "Let it Be film", "name": "Jazz Piano Song", "songwriter": "McCartney\nStarr", "notes": "", "vocal": "McCartney", "year": "1969"},
"jessiesdream": {"album": "Magical Mystery Tour", "name": "Jessie's Dream", "songwriter": "Lennon, McCartney, Harrison, Starr", "notes": "", "vocal": "Instrumental", "year": "1967"},
"johnnybgoode": {"album": "Live at the BBC", "name": "Johnny B. Goode", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1964"},
"julia": {"album": "The Beatles", "name": "Julia", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"junk": {"album": "Anthology 3", "name": "Junk", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"kansascityheyheyheyhey": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "Kansas City/Hey-Hey-Hey-Hey!", "songwriter": "Jerry Leiber and Mike Stoller/Little Richard", "notes": "Cover", "vocal": "McCartney", "year": "1964"},
"keepyourhandsoffmybaby": {"album": "Live at the BBC", "name": "Keep Your Hands Off My Baby", "songwriter": "Gerry Goffin\nCarole King", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"kommgibmirdeinehand": {"album": "UK: Rarities US: Something New", "name": "Komm, gib mir deine Hand", "songwriter": "Lennon\nMcCartney\nJean Nicolas\nHeinz Hellmer", "notes": "Non-album single\nGerman version of \"I Want to Hold Your Hand\",[12]\n\"Lady Madonna\"\"\"", "vocal": "Lennon, McCartney", "year": "1964"},
"leavemykittenalone": {"album": "Anthology 1", "name": "Leave My Kitten Alone", "songwriter": "Little Willie John\nTitus Turner\nJames McDougall", "notes": "Cover", "vocal": "Lennon", "year": "1964"},
"lendmeyourcomb": {"album": "Anthology 1", "name": "Lend Me Your Comb", "songwriter": "Kay Twomey\nFred Wise\nBen Weisman", "notes": "Cover", "vocal": "Lennon, McCartney", "year": "1963"},
"letitbe": {"album": "Let It Be", "name": "Let It Be", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"likedreamersdo": {"album": "Anthology 1", "name": "Like Dreamers Do", "songwriter": "McCartney", "notes": "Recorded by The Applejacks", "vocal": "McCartney", "year": "1962"},
"littlechild": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "Little Child", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1963"},
"lonesometearsinmyeyes": {"album": "Live at the BBC", "name": "Lonesome Tears in My Eyes", "songwriter": "Johnny Burnette\nDorsey Burnette\nPaul Burlison\nAl Mortimer", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"thelongandwindingroad": {"album": "Let It Be", "name": "The Long and Winding Road", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"longlonglong": {"album": "The Beatles", "name": "Long, Long, Long", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1968"},
"longtallsally": {"album": "UK: Long Tall Sally EP US: The Beatles' Second Album", "name": "Long Tall Sally", "songwriter": "Robert \"Bumps\" Blackwell\nEnotris Johnson\nLittle Richard", "notes": "Non-album single\nCover", "vocal": "McCartney", "year": "1964"},
"lookingglass": {"album": "", "name": "Looking Glass", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1962"},
"lovemedo": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Love Me Do", "songwriter": "McCartney\n(with Lennon)", "notes": "featuring Andy White on drums", "vocal": "McCartney, with Lennon", "year": "1962"},
"loveoftheloved": {"album": "", "name": "Love of the Loved", "songwriter": "McCartney\n(with Lennon)", "notes": "Single by Cilla Black\n(September 1963)", "vocal": "McCartney", "year": "1962"},
"loveyouto": {"album": "Revolver", "name": "Love You To", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1966"},
"lovelyrita": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Lovely Rita", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1967"},
"lucille": {"album": "Live at the BBC", "name": "Lucille", "songwriter": "Little Richard\nAlbert Collins", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"lucyintheskywithdiamonds": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Lucy in the Sky with Diamonds", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1967"},
"madman": {"album": "N/A", "name": "Madman", "songwriter": "Lennon", "notes": "From Get Back/Let It Be sessions", "vocal": "Lennon", "year": "1969"},
"maggiemae": {"album": "Let It Be", "name": "Maggie Mae", "songwriter": "Traditional, arr. Lennon, McCartney\nHarrison, Starr", "notes": "Cover", "vocal": "Lennon, with McCartney", "year": "1969"},
"magicalmysterytour": {"album": "Magical Mystery Tour", "name": "Magical Mystery Tour", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1967"},
"mailmanbringmenomoreblues": {"album": "Anthology 3", "name": "Mailman, Bring Me No More Blues", "songwriter": "Ruth Roberts\nBill Katz\nStanley Clayton", "notes": "Cover", "vocal": "Lennon", "year": "1969"},
"marthamydear": {"album": "The Beatles", "name": "Martha My Dear", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"matchbox": {"album": "UK: \"Long Tall Sally\" EP US: Something New", "name": "Matchbox", "songwriter": "Carl Perkins\nBlind Lemon Jefferson", "notes": "Cover", "vocal": "Starr", "year": "1964"},
"maxwellssilverhammer": {"album": "Abbey Road", "name": "Maxwell's Silver Hammer", "songwriter": "McCartney[56]", "notes": "", "vocal": "McCartney", "year": "1969"},
"meanmrmustard": {"album": "Abbey Road", "name": "Mean Mr. Mustard", "songwriter": "Lennon[58]", "notes": "", "vocal": "Lennon, with McCartney", "year": "1969"},
"memphistennessee": {"album": "Live at the BBC", "name": "Memphis, Tennessee", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"michelle": {"album": "Rubber Soul", "name": "Michelle", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1965"},
"misery": {"album": "UK: Please Please Me US: Introducing… The Beatles", "name": "Misery", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon and McCartney", "year": "1963"},
"moneythatswhatiwant": {"album": "UK: With the Beatles US: The Beatles Second Album", "name": "Money (That's What I Want)", "songwriter": "Berry Gordy\nJanie Bradford", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"moonlightbay": {"album": "Anthology 1", "name": "Moonlight Bay", "songwriter": "Percy Wenrich\nEdward Madden", "notes": "Performed on the Morecambe and Wise Show in 2/12/63", "vocal": "Lennon, McCartney, Harrison, Eric Morecambe, Ernie Wise", "year": "1963"},
"mothernaturesson": {"album": "The Beatles", "name": "Mother Nature's Son", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"mrmoonlight": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "Mr. Moonlight", "songwriter": "Roy Lee Johnson", "notes": "Cover", "vocal": "Lennon", "year": "1964"},
"thenightbefore": {"album": "Help!", "name": "The Night Before", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1965"},
"noreply": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "No Reply", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon, with McCartney", "year": "1964"},
"norwegianwoodthisbirdhasflown": {"album": "Rubber Soul", "name": "Norwegian Wood (This Bird Has Flown)", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1965"},
"notasecondtime": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "Not a Second Time", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1963"},
"notguilty": {"album": "Anthology 3", "name": "Not Guilty", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1968"},
"nothinshakinbuttheleavesonthetrees": {"album": "Live at the BBC", "name": "Nothin' Shakin' (But the Leaves on the Trees)", "songwriter": "Eddie Fontaine", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"nowhereman": {"album": "UK: Rubber Soul US: Yesterday and Today", "name": "Nowhere Man", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon, with McCartney and Harrison", "year": "1965"},
"obladioblada": {"album": "The Beatles", "name": "Ob-La-Di, Ob-La-Da", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"octopussgarden": {"album": "Abbey Road", "name": "Octopus's Garden", "songwriter": "Starkey[c]", "notes": "", "vocal": "Starr", "year": "1969"},
"ohdarling": {"album": "Abbey Road", "name": "Oh! Darling", "songwriter": "McCartney[32]", "notes": "", "vocal": "McCartney", "year": "1969"},
"oldbrownshoe": {"album": "UK: 1967–1970 US: Hey Jude", "name": "Old Brown Shoe", "songwriter": "Harrison", "notes": "Non-album single\nB-side of \"The Ballad of John and Yoko\",\n\"One After 909\"\"\"", "vocal": "Harrison", "year": "1969"},
"oneandoneistwo": {"album": "", "name": "One and One Is Two", "songwriter": "McCartney", "notes": "Single by The Strangers with Mike Shannon\n(May 1964)", "vocal": "McCartney", "year": "1964"},
"onlyanorthernsong": {"album": "Yellow Submarine", "name": "Only a Northern Song", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1967"},
"oohmysoul": {"album": "Live at the BBC", "name": "Ooh! My Soul", "songwriter": "Little Richard", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"paperbackwriter": {"album": "UK: A Collection of Beatles Oldies US: Hey Jude", "name": "Paperback Writer", "songwriter": "McCartney", "notes": "Non-album single", "vocal": "McCartney", "year": "1966"},
"pennylane": {"album": "Magical Mystery Tour", "name": "Penny Lane", "songwriter": "McCartney", "notes": "Double A-side single\nwith \"Strawberry Fields Forever\",[10]\n\"Piggies\"\"\"", "vocal": "McCartney", "year": "1966"},
"pleasemrpostman": {"album": "UK: With the Beatles US: The Beatles' Second Album", "name": "Please Mr. Postman", "songwriter": "Georgia Dobbins\nWilliam Garrett\nBrian Holland\nRobert Bateman\nFreddie Gorman", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"pleasepleaseme": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Please Please Me", "songwriter": "Lennon", "notes": "Single", "vocal": "Lennon and McCartney", "year": "1962"},
"polythenepam": {"album": "Abbey Road", "name": "Polythene Pam", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1969"},
"psiloveyou": {"album": "UK: Please Please Me US: The Early Beatles", "name": "P.S. I Love You", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1962"},
"rain": {"album": "UK: Rarities US: Hey Jude", "name": "Rain", "songwriter": "Lennon", "notes": "Non-album single\nB-side to \"Paperback Writer\",\n\"Real Love\"\"\"", "vocal": "Lennon", "year": "1966"},
"revolution": {"album": "UK: 1967-1970 US: Hey Jude", "name": "Revolution", "songwriter": "Lennon", "notes": "Non-album single\nB-side to \"Hey Jude\"", "vocal": "Lennon", "year": "1968"},
"revolution": {"album": "The Beatles", "name": "Revolution 1", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"revolution": {"album": "The Beatles", "name": "Revolution 9", "songwriter": "Lennon\n(with Ono and Harrison)", "notes": "", "vocal": "Sound Collage", "year": "1968"},
"ripitupshakerattleandrollbluesuedeshoes": {"album": "Anthology 3", "name": "Rip It Up / Shake, Rattle, and Roll / Blue Suede Shoes", "songwriter": "Robert Blackwell, John Marascalco (\"Rip It Up\")\nCharles Calhoun(\"Shake, Rattle, and Roll\")\nCarl Perkins (\"Blue Suede Shoes\")", "notes": "Cover", "vocal": "Lennon, McCartney", "year": "1969"},
"rockandrollmusic": {"album": "UK: Beatles for Sale US: Beatles '65", "name": "Rock and Roll Music", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1964"},
"rockyraccoon": {"album": "The Beatles", "name": "Rocky Raccoon", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney", "year": "1968"},
"rolloverbeethoven": {"album": "UK: With the Beatles US: The Beatles' Second Album", "name": "Roll Over Beethoven", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"runforyourlife": {"album": "Rubber Soul", "name": "Run for Your Life", "songwriter": "Lennon\n(with McCartney)", "notes": "", "vocal": "Lennon", "year": "1965"},
"savoytruffle": {"album": "The Beatles", "name": "Savoy Truffle", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1968"},
"searchin": {"album": "Anthology 1", "name": "Searchin'", "songwriter": "Jerry Leiber and Mike Stoller", "notes": "Cover", "vocal": "McCartney", "year": "1962"},
"septemberintherain": {"album": "", "name": "September in the Rain", "songwriter": "Al Dubin\nHarry Warren", "notes": "Cover", "vocal": "McCartney", "year": "1962"},
"sexysadie": {"album": "The Beatles", "name": "Sexy Sadie", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"sgtpepperslonelyheartsclubband": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Sgt. Pepper's Lonely Hearts Club Band", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, with Lennon, Harrison and Starr", "year": "1967"},
"sgtpepperslonelyheartsclubbandreprise": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Sgt. Pepper's Lonely Hearts Club Band (Reprise)", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, Lennon, Harrison, Starr", "year": "1967"},
"shakininthesixties": {"album": "Unreleased", "name": "Shakin' in the Sixties", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1969"},
"shecameinthroughthebathroomwindow": {"album": "Abbey Road", "name": "She Came in Through the Bathroom Window", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1969"},
"shelovesyou": {"album": "UK: A Collection of Beatles Oldies US: The Beatles Second Album", "name": "She Loves You", "songwriter": "Lennon\nMcCartney", "notes": "Non-album single", "vocal": "Lennon, McCartney", "year": "1963"},
"shesaidshesaid": {"album": "Revolver", "name": "She Said She Said", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1966"},
"shesawoman": {"album": "UK: Rarities US: Beatles '65", "name": "She's a Woman", "songwriter": "McCartney\n(with Lennon)", "notes": "Non-album single\nB-side to \"I Feel Fine\"", "vocal": "McCartney", "year": "1964"},
"shesleavinghome": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "She's Leaving Home", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1967"},
"thesheikofaraby": {"album": "Anthology 1", "name": "The Sheik of Araby", "songwriter": "Harry B. Smith\nFrancis Wheeler\nTed Snyder", "notes": "Cover", "vocal": "Harrison", "year": "1962"},
"ashotofrhythmandblues": {"album": "Live at the BBC", "name": "A Shot of Rhythm and Blues", "songwriter": "Terry Thompson", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"shout": {"album": "Anthology 1", "name": "Shout", "songwriter": "Rudolph Isley\nRonald Isley\nO'Kelly Isley Jr.", "notes": "Cover", "vocal": "Lennon, McCartney, Harrison, Starr", "year": "1964"},
"sieliebtdich": {"album": "UK: Rarities US: Rarities", "name": "Sie liebt dich", "songwriter": "Lennon\nMcCartney\nJean Nicolas\nLee Montogue", "notes": "Non-album single\nGerman version of \"She Loves You\"", "vocal": "Lennon, McCartney", "year": "1964"},
"slowdown": {"album": "UK: \"Long Tall Sally\" EP US: Something New", "name": "Slow Down", "songwriter": "Larry Williams", "notes": "Non-album single\nB-side of \"Matchbox\"\nCover", "vocal": "Lennon", "year": "1964"},
"sohowcomenoonelovesme": {"album": "Live at the BBC", "name": "So How Come (No One Loves Me)", "songwriter": "Felice and Boudleaux Bryant", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"soldieroflovelaydownyourarms": {"album": "Live at the BBC", "name": "Soldier of Love (Lay Down Your Arms)", "songwriter": "Buzz Cason\nTony Moon", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"someotherguy": {"album": "Live at the BBC", "name": "Some Other Guy", "songwriter": "Jerry Leiber and Mike Stoller\nRichie Barrett", "notes": "Cover", "vocal": "Lennon, McCartney", "year": "1963"},
"something": {"album": "Abbey Road", "name": "Something", "songwriter": "Harrison", "notes": "Double A-side single\nwith \"Come Together\",[34]\n\"Sour Milk Sea\"\"\"", "vocal": "Harrison", "year": "1969"},
"stepinsidelovelosparanoias": {"album": "Anthology 3", "name": "Step Inside Love/Los Paranoias", "songwriter": "McCartney (\"Step Inside Love\")\nLennon–McCartney\nHarrison–Starr (\"Los Paranoias\")", "notes": "\"Step Inside Love\" was recorded by Cilla Black\n(1968)", "vocal": "McCartney", "year": "1968"},
"strawberryfieldsforever": {"album": "Magical Mystery Tour", "name": "Strawberry Fields Forever", "songwriter": "Lennon", "notes": "Double A-side single\n(with \"Penny Lane\")", "vocal": "Lennon", "year": "1966"},
"sunking": {"album": "Abbey Road", "name": "Sun King", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney and Harrison", "year": "1969"},
"suretofallinlovewithyou": {"album": "Live at the BBC", "name": "Sure to Fall (in Love with You)", "songwriter": "Carl Perkins\nQuinton Claunch\nBill Cantrell", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"sweetlittlesixteen": {"album": "Live at the BBC", "name": "Sweet Little Sixteen", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"takegoodcareofmybaby": {"album": "", "name": "Take Good Care of My Baby", "songwriter": "Gerry Goffin\nCarole King", "notes": "Cover", "vocal": "Harrison", "year": "1962"},
"takingatriptocarolina": {"album": "Let It Be... Naked - Fly on the Wall bonus disc", "name": "Taking a Trip to Carolina", "songwriter": "Starr", "notes": "", "vocal": "Starr", "year": "1969"},
"atasteofhoney": {"album": "UK: Please Please Me US: The Early Beatles", "name": "A Taste of Honey", "songwriter": "Bobby Scott\nRic Marlow", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"taxman": {"album": "Revolver", "name": "Taxman", "songwriter": "Harrison", "notes": "McCartney plays guitar solo", "vocal": "Harrison, with Lennon and McCartney", "year": "1966"},
"teddyboy": {"album": "Anthology 3", "name": "Teddy Boy", "songwriter": "McCartney", "notes": "\"Let It Be\" outtake", "vocal": "McCartney", "year": "1969"},
"tellmewhatyousee": {"album": "UK: Help! US: Beatles VI", "name": "Tell Me What You See", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney, with Lennon", "year": "1965"},
"tellmewhy": {"album": "UK: A Hard Day's Night US: Something New", "name": "Tell Me Why", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1964"},
"thankyougirl": {"album": "UK: Rarities US: The Beatles Second Album", "name": "Thank You Girl", "songwriter": "Lennon\nMcCartney", "notes": "Non-album single\nB-side of \"From Me To You\",[38]\n\"That Means a Lot\"\"\"", "vocal": "Lennon, McCartney", "year": "1963"},
"thatllbetheday": {"album": "Anthology 1", "name": "That'll Be the Day", "songwriter": "Jerry Allison\nBuddy Holly\nNorman Petty", "notes": "Cover", "vocal": "Lennon", "year": "1958"},
"thatsallrightmama": {"album": "Live at the BBC", "name": "That’s All Right (Mama)", "songwriter": "Arthur Crudup", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"theresaplace": {"album": "UK: Please Please Me US: Rarities", "name": "There's a Place", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, McCartney", "year": "1963"},
"thingswesaidtoday": {"album": "UK: A Hard Day's Night US: Something New", "name": "Things We Said Today", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1964"},
"thinkforyourself": {"album": "Rubber Soul", "name": "Think for Yourself", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1965"},
"thisboy": {"album": "UK: Rarities US: Meet the Beatles!", "name": "This Boy", "songwriter": "Lennon", "notes": "Non-album single\nB-side of \"I Want To Hold Your Hand\",[8]\n\"Three Cool Cats\"\"\"", "vocal": "Lennon, with McCartney and Harrison", "year": "1963"},
"tickettoride": {"album": "Help!", "name": "Ticket to Ride", "songwriter": "Lennon", "notes": "", "vocal": "Lennon, with McCartney", "year": "1965"},
"tilltherewasyou": {"album": "UK: With the Beatles US: Meet the Beatles!", "name": "Till There Was You", "songwriter": "Meredith Willson", "notes": "Cover", "vocal": "McCartney", "year": "1963"},
"tipofmytongue": {"album": "Unreleased", "name": "Tip of My Tongue", "songwriter": "Lennon\nMcCartney", "notes": "Recorded by Tommy Quickly\n(Released in 1963)", "vocal": "Lennon, McCartney", "year": ""},
"toknowheristoloveher": {"album": "Live at the BBC", "name": "To Know Her is to Love Her", "songwriter": "Phil Spector", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"tomorrowneverknows": {"album": "Revolver", "name": "Tomorrow Never Knows", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1966"},
"toomuchmonkeybusiness": {"album": "Live at the BBC", "name": "Too Much Monkey Business", "songwriter": "Chuck Berry", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"twistandshout": {"album": "UK: Please Please Me US: The Early Beatles", "name": "Twist and Shout", "songwriter": "Phil Medley\nBert Berns", "notes": "Cover", "vocal": "Lennon", "year": "1963"},
"twoofus": {"album": "Let It Be", "name": "Two of Us", "songwriter": "McCartney", "notes": "", "vocal": "McCartney, with Lennon", "year": "1969"},
"wait": {"album": "Rubber Soul", "name": "Wait", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "McCartney and Lennon", "year": "1965"},
"watchingrainbows": {"album": "", "name": "Watching Rainbows", "songwriter": "Lennon\nand McCartney", "notes": "", "vocal": "Lennon", "year": "1969"},
"wecanworkitout": {"album": "UK: A Collection of Beatles Oldies US: Yesterday and Today", "name": "We Can Work It Out", "songwriter": "McCartney\n(with Lennon)", "notes": "Non-album single\nDouble A-side with \"Day Tripper\"", "vocal": "McCartney, with Lennon", "year": "1965"},
"whatgoeson": {"album": "UK: Rubber Soul US: Yesterday and Today", "name": "What Goes On", "songwriter": "Lennon\nMcCartney\nStarkey[d]", "notes": "", "vocal": "Starr", "year": "1965"},
"whatyouredoing": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "What You're Doing", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1964"},
"whatsthenewmaryjane": {"album": "Anthology 3", "name": "What's The New Mary Jane", "songwriter": "Lennon", "notes": "\"White Album\" outtake", "vocal": "Lennon", "year": "1968"},
"whenigethome": {"album": "UK: A Hard Day's Night US: Something New", "name": "When I Get Home", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1964"},
"whenimsixtyfour": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "When I'm Sixty-Four", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1966"},
"whilemyguitargentlyweeps": {"album": "The Beatles", "name": "While My Guitar Gently Weeps", "songwriter": "Harrison", "notes": "Eric Clapton plays lead guitar\n(uncredited)", "vocal": "Harrison", "year": "1968"},
"whydontwedoitintheroad": {"album": "The Beatles", "name": "Why Don't We Do It in the Road?", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"wildhoneypie": {"album": "The Beatles", "name": "Wild Honey Pie", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1968"},
"withalittlehelpfrommyfriends": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "With a Little Help from My Friends", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Starr, with Lennon and McCartney", "year": "1967"},
"withinyouwithoutyou": {"album": "Sgt. Pepper's Lonely Hearts Club Band", "name": "Within You Without You", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1967"},
"woman": {"album": "Let It Be film", "name": "Woman", "songwriter": "McCartney (as Bernard Webb)", "notes": "Single by Peter and Gordon\n(January 1966)", "vocal": "McCartney", "year": "1965"},
"theword": {"album": "Rubber Soul", "name": "The Word", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "Lennon, with McCartney and Harrison", "year": "1965"},
"wordsoflove": {"album": "UK: Beatles for Sale US: Beatles VI", "name": "Words of Love", "songwriter": "Buddy Holly", "notes": "Cover", "vocal": "Lennon, McCartney", "year": "1964"},
"yellowsubmarine": {"album": "Revolver", "name": "Yellow Submarine", "songwriter": "McCartney\n(with Lennon)", "notes": "", "vocal": "Starr", "year": "1966"},
"yerblues": {"album": "The Beatles", "name": "Yer Blues", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1968"},
"yesitis": {"album": "UK: Rarities US: Beatles VI", "name": "Yes It Is", "songwriter": "Lennon", "notes": "Non-album single\nB-side of \"Ticket to Ride\",[39]\n\"Yesterday\"\"\"", "vocal": "Lennon, McCartney and Harrison", "year": "1965"},
"youcantdothat": {"album": "UK: A Hard Day's Night US: The Beatles Second Album", "name": "You Can't Do That", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1964"},
"youknowmynamelookupthenumber": {"album": "UK: Rarities US: Rarities", "name": "You Know My Name (Look Up the Number)", "songwriter": "Lennon\n(with McCartney)", "notes": "Non-album single\nB-side of \"Let It Be\"", "vocal": "Lennon, McCartney", "year": "1967"},
"youknowwhattodo": {"album": "Anthology 1", "name": "You Know What to Do", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1964"},
"youlikemetoomuch": {"album": "UK: Help! US: Beatles VI", "name": "You Like Me Too Much", "songwriter": "Harrison", "notes": "", "vocal": "Harrison", "year": "1965"},
"younevergivemeyourmoney": {"album": "Abbey Road", "name": "You Never Give Me Your Money", "songwriter": "McCartney[61]", "notes": "", "vocal": "McCartney", "year": "1969"},
"youwontseeme": {"album": "Rubber Soul", "name": "You Won't See Me", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1965"},
"youllbemine": {"album": "Anthology 1", "name": "You'll Be Mine", "songwriter": "Lennon\nMcCartney", "notes": "", "vocal": "McCartney", "year": "1960"},
"youngblood": {"album": "Live at the BBC", "name": "Young Blood", "songwriter": "Jerry Leiber and Mike Stoller", "notes": "Cover", "vocal": "Harrison", "year": "1963"},
"yourmothershouldknow": {"album": "Magical Mystery Tour", "name": "Your Mother Should Know", "songwriter": "McCartney", "notes": "", "vocal": "McCartney", "year": "1967"},
"youregoingtolosethatgirl": {"album": "Help!", "name": "You're Going to Lose That Girl", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1965"},
"youvegottohideyourloveaway": {"album": "Help!", "name": "You've Got to Hide Your Love Away", "songwriter": "Lennon", "notes": "", "vocal": "Lennon", "year": "1965"},
"youvereallygotaholdonme": {"album": "UK: With the Beatles US: The Beatles Second Album", "name": "You've Really Got a Hold on Me", "songwriter": "Smokey Robinson", "notes": "Cover", "vocal": "Lennon and Harrison", "year": "1963"},
}

re_brackets = re.compile(r'\([^()]+\)')

DEBUG = os.environ.get('BS_DEBUG', False)

def debugp(s):
    if DEBUG:
        print('DEBUG: ' + s)

min_ratio = 0.75

def match_song(query):
    # remove `(xxx)`
    query = re_brackets.sub('', query)
    # keep only alpha
    sig = ''.join(i for i in query if i.isalpha()).lower()
    s = songs.get(sig)
    if s:
        return s
    debugp('no direct signature match')
    compares = []
    for k, v in songs.items():
        ratio = SequenceMatcher(None, k, sig).ratio()
        compares.append((ratio, v))
    top = sorted(compares, key=lambda x: x[0], reverse=True)[0]
    debugp('closest match: {}'.format(top))
    if top[0] > min_ratio:
        return top[1]
    debugp('top ratio is under {}, nothing really matched'.format(min_ratio))

def main():
    fmt = os.environ.get('BS_FMT', '{vocal} - {year}')
    try:
        query = sys.argv[1]
    except IndexError:
        print('Usage: beatles_searcher.py <query>')
        sys.exit(1)
    s = match_song(query)
    if s:
        print(fmt.format(**s) + '|' + s['name'])
    else:
        sys.exit(1)

main()
